version: "3.8"
services:


  postgres:
    image: postgres:16
    restart: always
    command: postgres -c 'max_connections=1100'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=defaultdb
